export enum IssueTypeEnum {
  FEATURE = "FEATURE",
  BUG = "BUG",
  ENHANCEMENT = "ENHANCEMENT",
  REFACTOR = "REFACTOR",
  DOCUMENTATION = "DOCUMENTATION",
  TASK = "TASK",
  CHORE = "CHORE",
  QUESTION = "QUESTION",
  SUPPORT = "SUPPORT",
  SECURITY = "SECURITY",
  PERFORMANCE = "PERFORMANCE",
  UX = "UX",
  DEPLOYMENT = "DEPLOYMENT",
  TESTING = "TESTING",
  CI_CD = "CI_CD",
  UNCATEGORIZED = "UNCATEGORIZED",
}

export enum IssueStatusEnum {
  IN_BACKLOG = "IN_BACKLOG",
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
}

export enum IssuePriorityEnum {
    HIGH = "HIGH",
    LOW = "LOW",
    MEDIUM = "MEDIUM"
}